#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
RUNTIME_ENV="${DATARULES_RUNTIME_ENV:-$ROOT/storage/runtime.env}"

mkdir -p "$(dirname "$RUNTIME_ENV")"

if [[ -n "${DATARULES_SECRET_KEY:-}" ]]; then
  exit 0
fi

if [[ -f "$RUNTIME_ENV" ]] && grep -q '^DATARULES_SECRET_KEY=' "$RUNTIME_ENV"; then
  chmod 600 "$RUNTIME_ENV"
  exit 0
fi

if [[ ! -x "$ROOT/.venv/bin/python" ]]; then
  echo "Missing .venv. Run scripts/setup_venv.sh first." >&2
  exit 1
fi

secret="$("$ROOT/.venv/bin/python" - <<'PY'
from cryptography.fernet import Fernet

print(Fernet.generate_key().decode())
PY
)"

umask 077
tmp="${RUNTIME_ENV}.tmp"
{
  printf '# Auto-generated by scripts/ensure_runtime_env.sh. Do not commit.\n'
  printf 'DATARULES_SECRET_KEY=%s\n' "$secret"
} > "$tmp"
mv "$tmp" "$RUNTIME_ENV"
chmod 600 "$RUNTIME_ENV"
